apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app-deployment-sidecar-api-go
  name: test-app-deployment-sidecar-api-go
spec:
  selector:
    matchLabels:
      app: test-app-deployment-sidecar-api-go
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app-deployment-sidecar-api-go
    spec:
      serviceAccountName: authn-k8s-sa
      containers:
        - name: test-app-deployment-sidecar-api-go
          image: quasys.jfrog.io/conjur-docker/test-app-go:0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CONJUR_SECRET_DB_PASSWORD
              value: secret/conjur-safe/db-passwords
          envFrom:
          - configMapRef:
              name: conjur-cm
          volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
        - image: cyberark/conjur-authn-k8s-client:0.21.0
          imagePullPolicy: IfNotPresent
          name: authenticator
          env:
            - name: CONJUR_AUTHN_LOGIN
              value: host/test-app-deployment-sidecar-api-go
            - name: CONTAINER_MODE
              value: sidecar
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: conjur-cm
          volumeMounts:
            - mountPath: /run/conjur
              name: conjur-access-token
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory